version: "3.8"
services:
  redis:
    build: redis/
    container_name: redis
    networks:
      - infra
    ports:
      - 6379:6379
    volumes:
      - ${PWD}/redis/data:/data
      - ${PWD}/redis/conf:/usr/local/etc/redis
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: redis-exporter
    networks:
      - infra
    ports:
      - 9121:9121
    environment:
      - REDIS_ADDR=redis://redis:6379

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - infra
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    networks:
      - infra
    ports:
      - 27017:27017

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    networks:
      - infra
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME="postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      - STATSD_PORT=9122

networks:
  infra:
    driver: bridge
