version: "3.8"
services:
  redis:
    build: redis/
    container_name: redis
    networks:
      - infra
    ports:
      - 6379:6379
    volumes:
      - ${PWD}/redis/data:/data
      - ${PWD}/redis/conf:/usr/local/etc/redis
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: redis-exporter
    networks:
      - infra
    ports:
      - 9121:9121
    environment:
      - REDIS_ADDR=redis://redis:6379

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - infra
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    networks:
      - infra
    ports:
      - 27017:27017

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@postgres:5432/users_dev?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - infra
    depends_on:
      - postgres

  gitlab:
    image: gitlab/gitlab-ce:17.1.2-ce.0
    container_name: gitlab
    restart: always
    networks:
      - infra
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - 80:80
      - 443:443
      - 2222:22
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - infra
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

networks:
  infra:
    driver: bridge
